export const IMG_CDN_URL = 
"https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const restaurantList = [
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "74453",
        name: "Domino's Pizza",
        uuid: "87727dbd-7f2b-4857-9763-359624165845",
        city: "21",
        area: "Athwa",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "bz9zkh2aqywjhpankb07",
        cuisines: ["Pizzas"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 45,
        minDeliveryTime: 45,
        maxDeliveryTime: 45,
        slaString: "45 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "dominos-pizza-majura-nondh-test_surat",
          city: "surat",
        },
        cityState: "21",
        address:
          "Shop 32 To 35, Sheetal Shopping Square,Near Lb Turning Point, Bhatar Road,MAJURA NONDH, Surat,GUJARAT-395001",
        locality: "Bhatar Road",
        parentId: 2456,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "74453",
          deliveryTime: 45,
          minDeliveryTime: 45,
          maxDeliveryTime: 45,
          lastMileTravel: 0,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "410476",
        name: "The Brooklyn Creamery - Healthy Ice Cream",
        uuid: "82e23b48-b6bd-4ee0-9746-06737ec062b0",
        city: "21",
        area: "althan bhatar",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "ldtibwymvzehvmdwl8la",
        cuisines: ["Desserts", "Ice Cream", "Healthy Food"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 31,
        minDeliveryTime: 30,
        maxDeliveryTime: 40,
        slaString: "30-40 MINS",
        lastMileTravel: 6.300000190734863,
        slugs: {
          restaurant: "the-brooklyn-creamery-low-cal-ice-cream-adajan-fc-adajan",
          city: "surat",
        },
        cityState: "21",
        address:
          "C paiki, Chalta no. 23, Guru Ashish Building, Ground Floor, Opp Kotyark Nagar, Rander Road, Surat 395005",
        locality: "Adajan FC",
        parentId: 236673,
        unserviceable: true,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "410476",
          deliveryTime: 31,
          minDeliveryTime: 30,
          maxDeliveryTime: 40,
          lastMileTravel: 6.300000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE_WITH_BANNER",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.4",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "81094",
        name: "Richie Rich Juices & Shakes",
        uuid: "40b0b55b-e9af-43e7-aeae-be1b012d0b1d",
        city: "21",
        area: "Athwa",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "nyp7yrzwc1dc2xqfkydk",
        cuisines: ["Ice Cream"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 40,
        slaString: "30-40 MINS",
        lastMileTravel: 5.599999904632568,
        slugs: {
          restaurant: "juices-shakes-by-richie-rich-athwa-athwa",
          city: "surat",
        },
        cityState: "21",
        address:
          "Richie Rich Building , Opposite Golden Square Complex, Parle Point, Athwa, Surat",
        locality: "Parle Point",
        parentId: 771,
        unserviceable: true,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "81094",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 40,
          lastMileTravel: 5.599999904632568,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE_WITH_BANNER",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "311443",
        name: "Siddhi Icecream & Thick Shake",
        uuid: "1ca3e8c2-e5da-4b59-8f7e-868991cb40b7",
        city: "21",
        area: "Nanpura",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "spd3y5gok3vvwqulgmda",
        cuisines: ["Ice Cream", "Juices", "Desserts", "Beverages"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 25,
        maxDeliveryTime: 35,
        slaString: "25-35 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "siddhi-icecream-athwa-athwa",
          city: "surat",
        },
        cityState: "21",
        address:
          "siddhi icecream, Kadampally Society, Timaliawad, Nanpura, Surat, Gujarat, India",
        locality: "Athwa",
        parentId: 387846,
        unserviceable: true,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "311443",
          deliveryTime: 30,
          minDeliveryTime: 25,
          maxDeliveryTime: 35,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE_WITH_BANNER",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.5",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "307070",
        name: "Pizza Pie",
        uuid: "68598bcb-7460-4466-a8b2-113158c6cf8c",
        city: "21",
        area: "Nanpura",
        totalRatingsString: "50+ ratings",
        cloudinaryImageId: "bvr70adr30ejyr5ua79k",
        cuisines: ["Pizzas"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 35,
        maxDeliveryTime: 45,
        slaString: "35-45 MINS",
        lastMileTravel: 4,
        slugs: {
          restaurant: "pizza-pie-athwa-athwa",
          city: "surat",
        },
        cityState: "21",
        address:
          "1/704 Sarang building, Nanpura New Rd, opposite river palace, near Ramji Mandir, Nanpura, Surat, Gujarat",
        locality: "Nanpura",
        parentId: 158854,
        unserviceable: true,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4 kms",
        hasSurge: false,
        sla: {
          restaurantId: "307070",
          deliveryTime: 37,
          minDeliveryTime: 35,
          maxDeliveryTime: 45,
          lastMileTravel: 4,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE_WITH_BANNER",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 50,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "76858",
        name: "Feeling Hungry",
        uuid: "45f9ea54-f3cf-4f6b-8d85-e3468657fe51",
        city: "21",
        area: "Athwa",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "oxsb5mr1xsmhnxhunjsc",
        cuisines: ["Chinese", "North Indian", "Biryani"],
        tags: [],
        costForTwo: 2000,
        costForTwoString: "₹20 FOR TWO",
        deliveryTime: 35,
        minDeliveryTime: 30,
        maxDeliveryTime: 40,
        slaString: "30-40 MINS",
        lastMileTravel: 3.700000047683716,
        slugs: {
          restaurant: "feeling-hungry-adajan-gam-adajan",
          city: "surat",
        },
        cityState: "21",
        address:
          "GF shop no 1, Babubhai Chambers, Beside Sardar Bridge , Athwagate, surat",
        locality: "Royal Residency, Adajan Gam",
        parentId: 79237,
        unserviceable: true,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "76858",
          deliveryTime: 35,
          minDeliveryTime: 30,
          maxDeliveryTime: 40,
          lastMileTravel: 3.700000047683716,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE_WITH_BANNER",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.2",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "617279",
        name: "Malaxmi Fast Food",
        uuid: "4848cb1b-b1c4-4a6e-9a6d-f96b781357db",
        city: "21",
        area: "Adajan",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "agkm7cflq72tkualhstb",
        cuisines: ["Fast Food", "Pizzas", "Snacks", "Beverages"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 44,
        minDeliveryTime: 40,
        maxDeliveryTime: 50,
        slaString: "40-50 MINS",
        lastMileTravel: 9.100000381469727,
        slugs: {
          restaurant: "mahalaxmi-fast-food-adajan-adajan-2",
          city: "surat",
        },
        cityState: "21",
        address: "shop no 15,palanpur food zone,opp.sai trith,pal gam suart",
        locality: "Palanpur Food Zone",
        parentId: 373635,
        unserviceable: true,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "9.1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "617279",
          deliveryTime: 44,
          minDeliveryTime: 40,
          maxDeliveryTime: 50,
          lastMileTravel: 9.100000381469727,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE_WITH_BANNER",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 20,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "469264",
        name: "Dessert House",
        uuid: "7a320917-c577-49cb-875a-1e585a3adbc1",
        city: "21",
        area: "Piplod",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "jegpumsjcmomksbr2sxr",
        cuisines: ["Desserts", "Ice Cream"],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 27,
        minDeliveryTime: 25,
        maxDeliveryTime: 35,
        slaString: "25-35 MINS",
        lastMileTravel: 6.199999809265137,
        slugs: {
          restaurant: "dessert-house-piplod-piplod",
          city: "surat",
        },
        cityState: "21",
        address:
          "SHOP NO 2, MARVELLA CORRIDOR OPP. C B PATEL HEALTH CLUB V.I.P ROAD, VESU",
        locality: "Piplod",
        parentId: 71430,
        unserviceable: true,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "469264",
          deliveryTime: 27,
          minDeliveryTime: 25,
          maxDeliveryTime: 35,
          lastMileTravel: 6.199999809265137,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE_WITH_BANNER",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.5",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "395204",
        name: "McDonald's Gourmet Burger Collection",
        uuid: "55c33a9b-bb51-4b9d-8c94-708d48b08ebd",
        city: "21",
        area: "Piplod",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "wzbo5xivr8hstl0vxzcm",
        cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 31,
        minDeliveryTime: 30,
        maxDeliveryTime: 40,
        slaString: "30-40 MINS",
        lastMileTravel: 8.199999809265137,
        slugs: {
          restaurant:
            "mcdonalds-gourmet-burger-collection-valentine-cinema-piplod",
          city: "surat",
        },
        cityState: "21",
        address:
          "MC Donalds Family Restaurant Valentine Mall Valentine Cine Vision Surat , Dhumas Road, Nr Govardhan Haveli, Surat 395007",
        locality: "Valentine Cinema",
        parentId: 10761,
        unserviceable: true,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "8.1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "395204",
          deliveryTime: 31,
          minDeliveryTime: 30,
          maxDeliveryTime: 40,
          lastMileTravel: 8.199999809265137,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE_WITH_BANNER",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "193541",
        name: "Behrouz Biryani",
        uuid: "abc2e9d1-df00-4449-bde3-4c35982d0ef3",
        city: "21",
        area: "Adajan Patiya",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "craozjakzx7sll2uracb",
        cuisines: [
          "Biryani",
          "Mughlai",
          "Lucknowi",
          "Hyderabadi",
          "Kebabs",
          "North Indian",
          "Persian",
          "Desserts",
        ],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 49,
        minDeliveryTime: 45,
        maxDeliveryTime: 55,
        slaString: "45-55 MINS",
        lastMileTravel: 6.400000095367432,
        slugs: {
          restaurant: "behrouz-biryani-adajan-adajan",
          city: "surat",
        },
        cityState: "21",
        address:
          "Chalta no 23, Ground Floor, Guru Ashish Building, Below Stallon Gym, Opp Kotyark Nagar, Near Navyug College, Adajan, Surat 395005",
        locality: "Nr Navyug College, Rander Road",
        parentId: 1803,
        unserviceable: true,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.4 kms",
        hasSurge: false,
        sla: {
          restaurantId: "193541",
          deliveryTime: 49,
          minDeliveryTime: 45,
          maxDeliveryTime: 55,
          lastMileTravel: 6.400000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE_WITH_BANNER",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "475510",
        name: "Momos House",
        uuid: "34320d9a-ffa7-450c-ad61-d50485306626",
        city: "21",
        area: "Piplod",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "vmold2zualdrrypxcvue",
        cuisines: ["Fast Food"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 31,
        minDeliveryTime: 30,
        maxDeliveryTime: 40,
        slaString: "30-40 MINS",
        lastMileTravel: 6.199999809265137,
        slugs: {
          restaurant: "momo’s-house-piplod-piplod",
          city: "surat",
        },
        cityState: "21",
        address:
          "SHOP NO - 2, MARVELLA CORRIDOR, OPP. C B PATEL HEALTH CLUB, V.I.P. ROAD, Surat,, Vesu , Surat Municipal Corporation, Surat Municipal Corporation, Gujarat - 395007",
        locality: "Vesu",
        parentId: 15884,
        unserviceable: true,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "475510",
          deliveryTime: 31,
          minDeliveryTime: 30,
          maxDeliveryTime: 40,
          lastMileTravel: 6.199999809265137,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE_WITH_BANNER",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "127596",
        name: "Sabir Chicken",
        uuid: "f0f49821-52ed-4435-9014-c845e964a3d8",
        city: "21",
        area: "Chowk Bazar",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "kilrdjqt8chduasii5ni",
        cuisines: ["North Indian", "Biryani"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 25,
        maxDeliveryTime: 35,
        slaString: "25-35 MINS",
        lastMileTravel: 4.300000190734863,
        slugs: {
          restaurant: "sabir-chicken-athwa-athwa",
          city: "surat",
        },
        cityState: "21",
        address:
          "Nehru Bridge, Behind Nagin Chand Hall, Chowk Bazar, Surat, Gujarat 395003",
        locality: "Chowk Bazar",
        parentId: 173978,
        unserviceable: true,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "127596",
          deliveryTime: 30,
          minDeliveryTime: 25,
          maxDeliveryTime: 35,
          lastMileTravel: 4.300000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE_WITH_BANNER",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "64656",
        name: "Mahesh Pav Bhaji",
        uuid: "ccfda4b9-82b1-4f22-9567-eb98c448b267",
        city: "21",
        area: "Adajan",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "84d3bea985f13bd980dc39c9c73bc87f",
        cuisines: ["Desserts", "Chinese", "South Indian", "Ice Cream", "Pizzas"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 36,
        minDeliveryTime: 35,
        maxDeliveryTime: 45,
        slaString: "35-45 MINS",
        lastMileTravel: 6.900000095367432,
        slugs: {
          restaurant: "mahesh-pav-bhaji-adajan-gam-adajan",
          city: "surat",
        },
        cityState: "21",
        address:
          "Shop 12, Garden View Apartment, Honey Park Road, Adajan Gam, Surat",
        locality: "Adajan Gam",
        parentId: 6553,
        unserviceable: true,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "30% off",
          shortDescriptionList: [
            {
              meta: "30% off | Use JUMBO",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "30% off up to ₹150 on orders above ₹400 | Use code JUMBO",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "30% OFF",
          shortDescriptionList: [
            {
              meta: "Use JUMBO",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "30% off up to ₹150 on orders above ₹400 | Use code JUMBO",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.9 kms",
        hasSurge: false,
        sla: {
          restaurantId: "64656",
          deliveryTime: 36,
          minDeliveryTime: 35,
          maxDeliveryTime: 45,
          lastMileTravel: 6.900000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE_WITH_BANNER",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "255204",
        name: "The Dango Cake Shop",
        uuid: "dbfd3f3c-77a6-4979-96c4-ce9863e54cdc",
        city: "21",
        area: "Galaxy Circle",
        totalRatingsString: "50+ ratings",
        cloudinaryImageId: "mnvfpsoealkflze4e5qi",
        cuisines: ["Bakery"],
        tags: [],
        costForTwo: 27000,
        costForTwoString: "₹270 FOR TWO",
        deliveryTime: 34,
        minDeliveryTime: 30,
        maxDeliveryTime: 40,
        slaString: "30-40 MINS",
        lastMileTravel: 7.699999809265137,
        slugs: {
          restaurant: "twisted-cake-live-cake-adajan-adajan",
          city: "surat",
        },
        cityState: "21",
        address: "44 La Victoria, galaxy circle pal Surat",
        locality: "Galaxy Circle",
        parentId: 207513,
        unserviceable: true,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.6 kms",
        hasSurge: false,
        sla: {
          restaurantId: "255204",
          deliveryTime: 34,
          minDeliveryTime: 30,
          maxDeliveryTime: 40,
          lastMileTravel: 7.699999809265137,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE_WITH_BANNER",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 50,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "664656",
        name: "Cheezylicious Cafe",
        uuid: "5880e561-10ed-4f96-990b-2251e2f09c82",
        city: "21",
        area: "Piplod",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "fda9ad56b9d62070fec105cd93693129",
        cuisines: [
          "Cafe",
          "Fast Food",
          "Chinese",
          "Snacks",
          "Italian",
          "Mexican",
        ],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 38,
        minDeliveryTime: 35,
        maxDeliveryTime: 45,
        slaString: "35-45 MINS",
        lastMileTravel: 7.599999904632568,
        slugs: {
          restaurant: "cheezylicious-cafe-piplod-piplod-2",
          city: "surat",
        },
        cityState: "21",
        address:
          "Shop no G10 ground floor, aagam square B/S Dream heritage, Canal road, Vesu",
        locality: "Dream heritage",
        parentId: 59292,
        unserviceable: true,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "664656",
          deliveryTime: 38,
          minDeliveryTime: 35,
          maxDeliveryTime: 45,
          lastMileTravel: 7.599999904632568,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE_WITH_BANNER",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 0,
        new: true,
      },
      subtype: "basic",
    },
];


export const userList = [
  {
    "login": "mojombo",
    "id": 1,
    "node_id": "MDQ6VXNlcjE=",
    "avatar_url": "https://avatars.githubusercontent.com/u/1?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mojombo",
    "html_url": "https://github.com/mojombo",
    "followers_url": "https://api.github.com/users/mojombo/followers",
    "following_url": "https://api.github.com/users/mojombo/following{/other_user}",
    "gists_url": "https://api.github.com/users/mojombo/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mojombo/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mojombo/subscriptions",
    "organizations_url": "https://api.github.com/users/mojombo/orgs",
    "repos_url": "https://api.github.com/users/mojombo/repos",
    "events_url": "https://api.github.com/users/mojombo/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mojombo/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "defunkt",
    "id": 2,
    "node_id": "MDQ6VXNlcjI=",
    "avatar_url": "https://avatars.githubusercontent.com/u/2?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/defunkt",
    "html_url": "https://github.com/defunkt",
    "followers_url": "https://api.github.com/users/defunkt/followers",
    "following_url": "https://api.github.com/users/defunkt/following{/other_user}",
    "gists_url": "https://api.github.com/users/defunkt/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/defunkt/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/defunkt/subscriptions",
    "organizations_url": "https://api.github.com/users/defunkt/orgs",
    "repos_url": "https://api.github.com/users/defunkt/repos",
    "events_url": "https://api.github.com/users/defunkt/events{/privacy}",
    "received_events_url": "https://api.github.com/users/defunkt/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "pjhyett",
    "id": 3,
    "node_id": "MDQ6VXNlcjM=",
    "avatar_url": "https://avatars.githubusercontent.com/u/3?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/pjhyett",
    "html_url": "https://github.com/pjhyett",
    "followers_url": "https://api.github.com/users/pjhyett/followers",
    "following_url": "https://api.github.com/users/pjhyett/following{/other_user}",
    "gists_url": "https://api.github.com/users/pjhyett/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/pjhyett/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/pjhyett/subscriptions",
    "organizations_url": "https://api.github.com/users/pjhyett/orgs",
    "repos_url": "https://api.github.com/users/pjhyett/repos",
    "events_url": "https://api.github.com/users/pjhyett/events{/privacy}",
    "received_events_url": "https://api.github.com/users/pjhyett/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "wycats",
    "id": 4,
    "node_id": "MDQ6VXNlcjQ=",
    "avatar_url": "https://avatars.githubusercontent.com/u/4?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/wycats",
    "html_url": "https://github.com/wycats",
    "followers_url": "https://api.github.com/users/wycats/followers",
    "following_url": "https://api.github.com/users/wycats/following{/other_user}",
    "gists_url": "https://api.github.com/users/wycats/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/wycats/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/wycats/subscriptions",
    "organizations_url": "https://api.github.com/users/wycats/orgs",
    "repos_url": "https://api.github.com/users/wycats/repos",
    "events_url": "https://api.github.com/users/wycats/events{/privacy}",
    "received_events_url": "https://api.github.com/users/wycats/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "ezmobius",
    "id": 5,
    "node_id": "MDQ6VXNlcjU=",
    "avatar_url": "https://avatars.githubusercontent.com/u/5?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ezmobius",
    "html_url": "https://github.com/ezmobius",
    "followers_url": "https://api.github.com/users/ezmobius/followers",
    "following_url": "https://api.github.com/users/ezmobius/following{/other_user}",
    "gists_url": "https://api.github.com/users/ezmobius/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ezmobius/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ezmobius/subscriptions",
    "organizations_url": "https://api.github.com/users/ezmobius/orgs",
    "repos_url": "https://api.github.com/users/ezmobius/repos",
    "events_url": "https://api.github.com/users/ezmobius/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ezmobius/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "ivey",
    "id": 6,
    "node_id": "MDQ6VXNlcjY=",
    "avatar_url": "https://avatars.githubusercontent.com/u/6?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ivey",
    "html_url": "https://github.com/ivey",
    "followers_url": "https://api.github.com/users/ivey/followers",
    "following_url": "https://api.github.com/users/ivey/following{/other_user}",
    "gists_url": "https://api.github.com/users/ivey/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ivey/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ivey/subscriptions",
    "organizations_url": "https://api.github.com/users/ivey/orgs",
    "repos_url": "https://api.github.com/users/ivey/repos",
    "events_url": "https://api.github.com/users/ivey/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ivey/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "evanphx",
    "id": 7,
    "node_id": "MDQ6VXNlcjc=",
    "avatar_url": "https://avatars.githubusercontent.com/u/7?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/evanphx",
    "html_url": "https://github.com/evanphx",
    "followers_url": "https://api.github.com/users/evanphx/followers",
    "following_url": "https://api.github.com/users/evanphx/following{/other_user}",
    "gists_url": "https://api.github.com/users/evanphx/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/evanphx/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/evanphx/subscriptions",
    "organizations_url": "https://api.github.com/users/evanphx/orgs",
    "repos_url": "https://api.github.com/users/evanphx/repos",
    "events_url": "https://api.github.com/users/evanphx/events{/privacy}",
    "received_events_url": "https://api.github.com/users/evanphx/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "vanpelt",
    "id": 17,
    "node_id": "MDQ6VXNlcjE3",
    "avatar_url": "https://avatars.githubusercontent.com/u/17?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/vanpelt",
    "html_url": "https://github.com/vanpelt",
    "followers_url": "https://api.github.com/users/vanpelt/followers",
    "following_url": "https://api.github.com/users/vanpelt/following{/other_user}",
    "gists_url": "https://api.github.com/users/vanpelt/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/vanpelt/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/vanpelt/subscriptions",
    "organizations_url": "https://api.github.com/users/vanpelt/orgs",
    "repos_url": "https://api.github.com/users/vanpelt/repos",
    "events_url": "https://api.github.com/users/vanpelt/events{/privacy}",
    "received_events_url": "https://api.github.com/users/vanpelt/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "wayneeseguin",
    "id": 18,
    "node_id": "MDQ6VXNlcjE4",
    "avatar_url": "https://avatars.githubusercontent.com/u/18?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/wayneeseguin",
    "html_url": "https://github.com/wayneeseguin",
    "followers_url": "https://api.github.com/users/wayneeseguin/followers",
    "following_url": "https://api.github.com/users/wayneeseguin/following{/other_user}",
    "gists_url": "https://api.github.com/users/wayneeseguin/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/wayneeseguin/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/wayneeseguin/subscriptions",
    "organizations_url": "https://api.github.com/users/wayneeseguin/orgs",
    "repos_url": "https://api.github.com/users/wayneeseguin/repos",
    "events_url": "https://api.github.com/users/wayneeseguin/events{/privacy}",
    "received_events_url": "https://api.github.com/users/wayneeseguin/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "brynary",
    "id": 19,
    "node_id": "MDQ6VXNlcjE5",
    "avatar_url": "https://avatars.githubusercontent.com/u/19?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/brynary",
    "html_url": "https://github.com/brynary",
    "followers_url": "https://api.github.com/users/brynary/followers",
    "following_url": "https://api.github.com/users/brynary/following{/other_user}",
    "gists_url": "https://api.github.com/users/brynary/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/brynary/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/brynary/subscriptions",
    "organizations_url": "https://api.github.com/users/brynary/orgs",
    "repos_url": "https://api.github.com/users/brynary/repos",
    "events_url": "https://api.github.com/users/brynary/events{/privacy}",
    "received_events_url": "https://api.github.com/users/brynary/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "kevinclark",
    "id": 20,
    "node_id": "MDQ6VXNlcjIw",
    "avatar_url": "https://avatars.githubusercontent.com/u/20?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kevinclark",
    "html_url": "https://github.com/kevinclark",
    "followers_url": "https://api.github.com/users/kevinclark/followers",
    "following_url": "https://api.github.com/users/kevinclark/following{/other_user}",
    "gists_url": "https://api.github.com/users/kevinclark/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kevinclark/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kevinclark/subscriptions",
    "organizations_url": "https://api.github.com/users/kevinclark/orgs",
    "repos_url": "https://api.github.com/users/kevinclark/repos",
    "events_url": "https://api.github.com/users/kevinclark/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kevinclark/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "technoweenie",
    "id": 21,
    "node_id": "MDQ6VXNlcjIx",
    "avatar_url": "https://avatars.githubusercontent.com/u/21?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/technoweenie",
    "html_url": "https://github.com/technoweenie",
    "followers_url": "https://api.github.com/users/technoweenie/followers",
    "following_url": "https://api.github.com/users/technoweenie/following{/other_user}",
    "gists_url": "https://api.github.com/users/technoweenie/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/technoweenie/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/technoweenie/subscriptions",
    "organizations_url": "https://api.github.com/users/technoweenie/orgs",
    "repos_url": "https://api.github.com/users/technoweenie/repos",
    "events_url": "https://api.github.com/users/technoweenie/events{/privacy}",
    "received_events_url": "https://api.github.com/users/technoweenie/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "macournoyer",
    "id": 22,
    "node_id": "MDQ6VXNlcjIy",
    "avatar_url": "https://avatars.githubusercontent.com/u/22?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/macournoyer",
    "html_url": "https://github.com/macournoyer",
    "followers_url": "https://api.github.com/users/macournoyer/followers",
    "following_url": "https://api.github.com/users/macournoyer/following{/other_user}",
    "gists_url": "https://api.github.com/users/macournoyer/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/macournoyer/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/macournoyer/subscriptions",
    "organizations_url": "https://api.github.com/users/macournoyer/orgs",
    "repos_url": "https://api.github.com/users/macournoyer/repos",
    "events_url": "https://api.github.com/users/macournoyer/events{/privacy}",
    "received_events_url": "https://api.github.com/users/macournoyer/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "takeo",
    "id": 23,
    "node_id": "MDQ6VXNlcjIz",
    "avatar_url": "https://avatars.githubusercontent.com/u/23?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/takeo",
    "html_url": "https://github.com/takeo",
    "followers_url": "https://api.github.com/users/takeo/followers",
    "following_url": "https://api.github.com/users/takeo/following{/other_user}",
    "gists_url": "https://api.github.com/users/takeo/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/takeo/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/takeo/subscriptions",
    "organizations_url": "https://api.github.com/users/takeo/orgs",
    "repos_url": "https://api.github.com/users/takeo/repos",
    "events_url": "https://api.github.com/users/takeo/events{/privacy}",
    "received_events_url": "https://api.github.com/users/takeo/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "caged",
    "id": 25,
    "node_id": "MDQ6VXNlcjI1",
    "avatar_url": "https://avatars.githubusercontent.com/u/25?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/caged",
    "html_url": "https://github.com/caged",
    "followers_url": "https://api.github.com/users/caged/followers",
    "following_url": "https://api.github.com/users/caged/following{/other_user}",
    "gists_url": "https://api.github.com/users/caged/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/caged/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/caged/subscriptions",
    "organizations_url": "https://api.github.com/users/caged/orgs",
    "repos_url": "https://api.github.com/users/caged/repos",
    "events_url": "https://api.github.com/users/caged/events{/privacy}",
    "received_events_url": "https://api.github.com/users/caged/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "topfunky",
    "id": 26,
    "node_id": "MDQ6VXNlcjI2",
    "avatar_url": "https://avatars.githubusercontent.com/u/26?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/topfunky",
    "html_url": "https://github.com/topfunky",
    "followers_url": "https://api.github.com/users/topfunky/followers",
    "following_url": "https://api.github.com/users/topfunky/following{/other_user}",
    "gists_url": "https://api.github.com/users/topfunky/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/topfunky/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/topfunky/subscriptions",
    "organizations_url": "https://api.github.com/users/topfunky/orgs",
    "repos_url": "https://api.github.com/users/topfunky/repos",
    "events_url": "https://api.github.com/users/topfunky/events{/privacy}",
    "received_events_url": "https://api.github.com/users/topfunky/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "anotherjesse",
    "id": 27,
    "node_id": "MDQ6VXNlcjI3",
    "avatar_url": "https://avatars.githubusercontent.com/u/27?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/anotherjesse",
    "html_url": "https://github.com/anotherjesse",
    "followers_url": "https://api.github.com/users/anotherjesse/followers",
    "following_url": "https://api.github.com/users/anotherjesse/following{/other_user}",
    "gists_url": "https://api.github.com/users/anotherjesse/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/anotherjesse/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/anotherjesse/subscriptions",
    "organizations_url": "https://api.github.com/users/anotherjesse/orgs",
    "repos_url": "https://api.github.com/users/anotherjesse/repos",
    "events_url": "https://api.github.com/users/anotherjesse/events{/privacy}",
    "received_events_url": "https://api.github.com/users/anotherjesse/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "roland",
    "id": 28,
    "node_id": "MDQ6VXNlcjI4",
    "avatar_url": "https://avatars.githubusercontent.com/u/28?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/roland",
    "html_url": "https://github.com/roland",
    "followers_url": "https://api.github.com/users/roland/followers",
    "following_url": "https://api.github.com/users/roland/following{/other_user}",
    "gists_url": "https://api.github.com/users/roland/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/roland/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/roland/subscriptions",
    "organizations_url": "https://api.github.com/users/roland/orgs",
    "repos_url": "https://api.github.com/users/roland/repos",
    "events_url": "https://api.github.com/users/roland/events{/privacy}",
    "received_events_url": "https://api.github.com/users/roland/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "lukas",
    "id": 29,
    "node_id": "MDQ6VXNlcjI5",
    "avatar_url": "https://avatars.githubusercontent.com/u/29?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/lukas",
    "html_url": "https://github.com/lukas",
    "followers_url": "https://api.github.com/users/lukas/followers",
    "following_url": "https://api.github.com/users/lukas/following{/other_user}",
    "gists_url": "https://api.github.com/users/lukas/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/lukas/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/lukas/subscriptions",
    "organizations_url": "https://api.github.com/users/lukas/orgs",
    "repos_url": "https://api.github.com/users/lukas/repos",
    "events_url": "https://api.github.com/users/lukas/events{/privacy}",
    "received_events_url": "https://api.github.com/users/lukas/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "fanvsfan",
    "id": 30,
    "node_id": "MDQ6VXNlcjMw",
    "avatar_url": "https://avatars.githubusercontent.com/u/30?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/fanvsfan",
    "html_url": "https://github.com/fanvsfan",
    "followers_url": "https://api.github.com/users/fanvsfan/followers",
    "following_url": "https://api.github.com/users/fanvsfan/following{/other_user}",
    "gists_url": "https://api.github.com/users/fanvsfan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/fanvsfan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/fanvsfan/subscriptions",
    "organizations_url": "https://api.github.com/users/fanvsfan/orgs",
    "repos_url": "https://api.github.com/users/fanvsfan/repos",
    "events_url": "https://api.github.com/users/fanvsfan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/fanvsfan/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "tomtt",
    "id": 31,
    "node_id": "MDQ6VXNlcjMx",
    "avatar_url": "https://avatars.githubusercontent.com/u/31?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tomtt",
    "html_url": "https://github.com/tomtt",
    "followers_url": "https://api.github.com/users/tomtt/followers",
    "following_url": "https://api.github.com/users/tomtt/following{/other_user}",
    "gists_url": "https://api.github.com/users/tomtt/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tomtt/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tomtt/subscriptions",
    "organizations_url": "https://api.github.com/users/tomtt/orgs",
    "repos_url": "https://api.github.com/users/tomtt/repos",
    "events_url": "https://api.github.com/users/tomtt/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tomtt/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "railsjitsu",
    "id": 32,
    "node_id": "MDQ6VXNlcjMy",
    "avatar_url": "https://avatars.githubusercontent.com/u/32?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/railsjitsu",
    "html_url": "https://github.com/railsjitsu",
    "followers_url": "https://api.github.com/users/railsjitsu/followers",
    "following_url": "https://api.github.com/users/railsjitsu/following{/other_user}",
    "gists_url": "https://api.github.com/users/railsjitsu/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/railsjitsu/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/railsjitsu/subscriptions",
    "organizations_url": "https://api.github.com/users/railsjitsu/orgs",
    "repos_url": "https://api.github.com/users/railsjitsu/repos",
    "events_url": "https://api.github.com/users/railsjitsu/events{/privacy}",
    "received_events_url": "https://api.github.com/users/railsjitsu/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "nitay",
    "id": 34,
    "node_id": "MDQ6VXNlcjM0",
    "avatar_url": "https://avatars.githubusercontent.com/u/34?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nitay",
    "html_url": "https://github.com/nitay",
    "followers_url": "https://api.github.com/users/nitay/followers",
    "following_url": "https://api.github.com/users/nitay/following{/other_user}",
    "gists_url": "https://api.github.com/users/nitay/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nitay/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nitay/subscriptions",
    "organizations_url": "https://api.github.com/users/nitay/orgs",
    "repos_url": "https://api.github.com/users/nitay/repos",
    "events_url": "https://api.github.com/users/nitay/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nitay/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "kevwil",
    "id": 35,
    "node_id": "MDQ6VXNlcjM1",
    "avatar_url": "https://avatars.githubusercontent.com/u/35?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kevwil",
    "html_url": "https://github.com/kevwil",
    "followers_url": "https://api.github.com/users/kevwil/followers",
    "following_url": "https://api.github.com/users/kevwil/following{/other_user}",
    "gists_url": "https://api.github.com/users/kevwil/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kevwil/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kevwil/subscriptions",
    "organizations_url": "https://api.github.com/users/kevwil/orgs",
    "repos_url": "https://api.github.com/users/kevwil/repos",
    "events_url": "https://api.github.com/users/kevwil/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kevwil/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "KirinDave",
    "id": 36,
    "node_id": "MDQ6VXNlcjM2",
    "avatar_url": "https://avatars.githubusercontent.com/u/36?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/KirinDave",
    "html_url": "https://github.com/KirinDave",
    "followers_url": "https://api.github.com/users/KirinDave/followers",
    "following_url": "https://api.github.com/users/KirinDave/following{/other_user}",
    "gists_url": "https://api.github.com/users/KirinDave/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/KirinDave/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/KirinDave/subscriptions",
    "organizations_url": "https://api.github.com/users/KirinDave/orgs",
    "repos_url": "https://api.github.com/users/KirinDave/repos",
    "events_url": "https://api.github.com/users/KirinDave/events{/privacy}",
    "received_events_url": "https://api.github.com/users/KirinDave/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "jamesgolick",
    "id": 37,
    "node_id": "MDQ6VXNlcjM3",
    "avatar_url": "https://avatars.githubusercontent.com/u/37?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jamesgolick",
    "html_url": "https://github.com/jamesgolick",
    "followers_url": "https://api.github.com/users/jamesgolick/followers",
    "following_url": "https://api.github.com/users/jamesgolick/following{/other_user}",
    "gists_url": "https://api.github.com/users/jamesgolick/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jamesgolick/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jamesgolick/subscriptions",
    "organizations_url": "https://api.github.com/users/jamesgolick/orgs",
    "repos_url": "https://api.github.com/users/jamesgolick/repos",
    "events_url": "https://api.github.com/users/jamesgolick/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jamesgolick/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "atmos",
    "id": 38,
    "node_id": "MDQ6VXNlcjM4",
    "avatar_url": "https://avatars.githubusercontent.com/u/38?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/atmos",
    "html_url": "https://github.com/atmos",
    "followers_url": "https://api.github.com/users/atmos/followers",
    "following_url": "https://api.github.com/users/atmos/following{/other_user}",
    "gists_url": "https://api.github.com/users/atmos/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/atmos/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/atmos/subscriptions",
    "organizations_url": "https://api.github.com/users/atmos/orgs",
    "repos_url": "https://api.github.com/users/atmos/repos",
    "events_url": "https://api.github.com/users/atmos/events{/privacy}",
    "received_events_url": "https://api.github.com/users/atmos/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "errfree",
    "id": 44,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjQ0",
    "avatar_url": "https://avatars.githubusercontent.com/u/44?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/errfree",
    "html_url": "https://github.com/errfree",
    "followers_url": "https://api.github.com/users/errfree/followers",
    "following_url": "https://api.github.com/users/errfree/following{/other_user}",
    "gists_url": "https://api.github.com/users/errfree/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/errfree/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/errfree/subscriptions",
    "organizations_url": "https://api.github.com/users/errfree/orgs",
    "repos_url": "https://api.github.com/users/errfree/repos",
    "events_url": "https://api.github.com/users/errfree/events{/privacy}",
    "received_events_url": "https://api.github.com/users/errfree/received_events",
    "type": "Organization",
    "site_admin": false
  },
  {
    "login": "mojodna",
    "id": 45,
    "node_id": "MDQ6VXNlcjQ1",
    "avatar_url": "https://avatars.githubusercontent.com/u/45?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mojodna",
    "html_url": "https://github.com/mojodna",
    "followers_url": "https://api.github.com/users/mojodna/followers",
    "following_url": "https://api.github.com/users/mojodna/following{/other_user}",
    "gists_url": "https://api.github.com/users/mojodna/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mojodna/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mojodna/subscriptions",
    "organizations_url": "https://api.github.com/users/mojodna/orgs",
    "repos_url": "https://api.github.com/users/mojodna/repos",
    "events_url": "https://api.github.com/users/mojodna/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mojodna/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "bmizerany",
    "id": 46,
    "node_id": "MDQ6VXNlcjQ2",
    "avatar_url": "https://avatars.githubusercontent.com/u/46?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/bmizerany",
    "html_url": "https://github.com/bmizerany",
    "followers_url": "https://api.github.com/users/bmizerany/followers",
    "following_url": "https://api.github.com/users/bmizerany/following{/other_user}",
    "gists_url": "https://api.github.com/users/bmizerany/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/bmizerany/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/bmizerany/subscriptions",
    "organizations_url": "https://api.github.com/users/bmizerany/orgs",
    "repos_url": "https://api.github.com/users/bmizerany/repos",
    "events_url": "https://api.github.com/users/bmizerany/events{/privacy}",
    "received_events_url": "https://api.github.com/users/bmizerany/received_events",
    "type": "User",
    "site_admin": false
  }
]

